[colors]
background = '#111117'
foreground = '#cac5cb'

cursor_bg = '#b6c4ff'
cursor_fg = '#111117'
cursor_border = '#b6c4ff'

selection_bg = '#7dcfff'
selection_fg = '#cac5cb'

ansi = ['#111117', '#ff7297', '#7fff94', '#fff972', '#9faef2', '#384376', '#B6C4FF', '#eff2ff']
brights = ['#999ba5', '#ff9fb8', '#a5ffb4', '#fffba5', '#c0ccff', '#cbd5ff', '#dee4ff', '#f8f9ff']
