#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

printf 'Xft.dpi: 144\nXcursor.size: 32\n' | xrdb -merge
#export GDK_SCALE=2
export GDK_DPI_SCALE=0.8             # cancel GTK's double font scaling on top of GDK_SCALE
export QT_AUTO_SCREEN_SCALE_FACTOR=1 # Qt apps (pavucontrol, qimgv) follow Xft.dpi
export XCURSOR_SIZE=32
xinput disable 14
wmname LG3D &

~/.config/bspwm/scripts/autostart.sh &
# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width 4

bspc config window_gap 8
bspc config top_padding 0
bspc config bottom_padding 0

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#bfc9f4"
bspc config normal_border_color "#1a1b26"

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
