#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

export GDK_SCALE=2
export GDK_DPI_SCALE=0.8
export QT_AUTO_SCREEN_SCALE_FACTOR=1.0
export XCURSOR_SIZE=42
export XDG_SESSION_TYPE=x11
export GTK_USE_PORTAL=1
export QT_QPA_PLATFORM=xcb

~/.config/bspwm/scripts/autostart.sh &
xsetroot -cursor_name left_ptr &
# Load base X resources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# Load active theme override if it exists
[ -f ~/.config/themes/.current ] &&
	xrdb -merge "$HOME/nux/home/config/themes/$(cat ~/.config/themes/.current)/st.Xresources" 2>/dev/null

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width 4

bspc config window_gap 12
bspc config top_padding 0
bspc config bottom_padding 0

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#bfc9f4"
bspc config normal_border_color "#13141c"

bspc config focus_follows_pointer true

wmname LG3D &
