#!/usr/bin/env sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

# --- Environment ---
export GDK_SCALE=2
export GDK_DPI_SCALE=0.8
export QT_SCALE_FACTOR=1.3
export GTK_USE_PORTAL=1
export XCURSOR_SIZE=48
export XCURSOR_THEME=Bibata-Modern-Ice
export ELECTRON_OZONE_PLATFORM_HINT=x11

# --- Startup ---
~/.config/bspwm/scripts/autostart.sh &
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &
touchegg &
wmname BSPWM &

# --- Workspaces ---
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# --- Appearance ---
bspc config border_width 4
bspc config window_gap 12
bspc config top_padding 0
bspc config bottom_padding 0
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#bfc9f4"
bspc config normal_border_color "#13141c"

# --- Behavior ---
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config split_ratio 0.5
bspc config focus_follows_pointer true

# --- Window rules ---
bspc rule -a Gtk-file-chooser state=floating rectangle=1600x1100+1120+650 center=true
bspc rule -a Pavucontrol state=floating rectangle=1400x1000+1220+700
bspc rule -a BoltLauncher state=floating center=true rectangle=1600x1100+1120+650
bspc rule -a net-runelite-client-RuneLite state=floating center=true
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a org.gnome.FileRoller state=floating
bspc rule -a scratchpad state=floating
