match = "class_i = 'skippy-xd'";
blur-background = false;
corner-radius = 8;
opacity = 1.0;
dim = 0.3;
shadow = false;
animations = (
    {
        triggers = ["close", "hide"];
        opacity = 1.0;
        preset = "fly-out";
        direction = "left";
        delay = 0.12;
        duration = 0.8;
    },
    {
        triggers = ["open", "show"];
        opacity = 1.0;
        preset = "fly-in";
        delay = 3;
        direction = "left";
        duration = 0.2;
    },
);
